FROM oven/bun:latest AS runtime

WORKDIR /app

COPY package.json bun.lock ./

RUN bun install

COPY . .

RUN bun run build

ENV HOST=0.0.0.0
ENV PORT=3000

EXPOSE 3000

CMD ["astro", "dev", "--port", "3000", "--host", "0.0.0.0"]

