FROM oven/bun:latest as build
WORKDIR /app

COPY package*.json ./
RUN bun install

COPY . .
RUN bun run build

FROM oven/bun:latest as prod
WORKDIR /app
COPY --from=build /app/dist ./dist

EXPOSE 3000
CMD ["bunx", "serve", "./dist", "-l", "3000"]

